### ISSUE TITLE
github pages

### ISSUE THREAD

**Issue by anotherjesse** [robbykraft/SVG#1]
Really like what you have done!

If you want to have the examples hosted on github.io, it is pretty easy, I've verified it can be done in a fork:  https://anotherjesse.github.io/SVG/ & https://anotherjesse.github.io/SVG/examples/1_intro-A-without.html

1. enable github pages on the master branch
2. create simple examples/index.html that has a list of the examples (with better descriptions than I have done)
3. link examples/index.html on the main index.md
4. add link to http://robbykraft.github.io/SVG/ by clicking the description at the top of https://github.com/anotherjesse/SVG

Apologies if this is unwanted info. 

Best,
Jesse

**Comment by robbykraft** [comment]
ahh thank you!! yes this sounds great. very welcomed. I'm following your steps right now.

**Comment by robbykraft** [comment]
okay, i linked the examples directly from readme.md instead of making a intermediary html file, maybe i'm losing something by doing this. haven't used gh pages much. also I didn't quite follow #4. but it's working great! thanks very much!!
Robby
